// "use client"
import { Inter, Ubuntu_Mono } from 'next/font/google'
import './globals.css'
// import { useEffect, useState } from "react";
import AppProvider from "./Context"
const inter = Inter({ subsets: ['latin'] })
const ubuntu_Mono = Ubuntu_Mono({ subsets: ['latin'], weight: '700' })
import Navbar from './components/Navbar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const [login,SetLogin] = useState(false)


  return (
    <html lang="en">
      <body className={ubuntu_Mono.className}>
        <div className='px-3 py-4'>
          <AppProvider>
            <Navbar />
            <main className="flex min-h-screen flex-col p-6">
              {children}
            </main>
          </AppProvider>
        </div>
      </body>
    </html>
  )
}
